"""
Accuracy tests for WhisperTranscriber.

Marked @pytest.mark.slow — these load the model and take O(seconds).

Fixture audio is generated by:
    cd audio-subtitles && python tests/generate_fixtures.py

User-provided MP3s live in mp3-files/; their ground truth .txt files live in
tests/fixtures/ and must be filled in manually (see fixtures/README.md).
"""
import pytest

from tests.helpers import wer, cer, segments_to_text

# (audio_path_relative_to_root, ground_truth_fixture)
TTS_FIXTURES = [
    ("tests/fixtures/clean_speech.wav", "tests/fixtures/clean_speech.txt"),
    ("tests/fixtures/numbers.wav", "tests/fixtures/numbers.txt"),
]

MP3_FIXTURES = [
    ("mp3-files/10_Second_Pep_Talk.mp3", "tests/fixtures/pep_talk.txt"),
    ("mp3-files/wednesday_dialogue.mp3", "tests/fixtures/wednesday_dialogue.txt"),
    # music fixture intentionally omitted here — transcription without vocal
    # separation is expected to be poor; tested separately in test_pipeline_e2e.py
]

WER_THRESHOLD = 0.10   # 10% — small model on clean speech
MP3_WER_THRESHOLD = 0.25  # 25% — real-world audio, no preprocessing beyond resample


def _load_ground_truth(root, truth_rel):
    path = root / truth_rel
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8").strip()


# ── TTS fixtures (generated, deterministic) ────────────────────────────────

@pytest.mark.slow
class TestWhisperTTSAccuracy:
    @pytest.mark.parametrize("audio_rel,truth_rel", TTS_FIXTURES)
    def test_wer(self, whisper_transcriber, fixtures_dir, audio_rel, truth_rel):
        root = fixtures_dir.parent.parent  # audio-subtitles/
        audio_path = root / audio_rel
        if not audio_path.exists():
            pytest.skip(
                f"TTS fixture missing: {audio_path}\n"
                "  Run: cd audio-subtitles && python tests/generate_fixtures.py"
            )
        reference = _load_ground_truth(root, truth_rel)
        assert reference, f"Ground truth file empty or missing: {truth_rel}"

        segments = whisper_transcriber.transcribe(str(audio_path))
        hypothesis = segments_to_text(segments)
        score = wer(reference, hypothesis)

        assert score < WER_THRESHOLD, (
            f"WER {score:.1%} exceeds threshold {WER_THRESHOLD:.0%}\n"
            f"  Reference:  {reference}\n"
            f"  Hypothesis: {hypothesis}"
        )

    @pytest.mark.parametrize("audio_rel,truth_rel", TTS_FIXTURES)
    def test_segments_nonempty(self, whisper_transcriber, fixtures_dir, audio_rel, truth_rel):
        root = fixtures_dir.parent.parent
        audio_path = root / audio_rel
        if not audio_path.exists():
            pytest.skip(f"TTS fixture missing: {audio_path}")

        segments = whisper_transcriber.transcribe(str(audio_path))
        assert len(segments) > 0

    @pytest.mark.parametrize("audio_rel,truth_rel", TTS_FIXTURES)
    def test_segments_ordered_and_valid(self, whisper_transcriber, fixtures_dir, audio_rel, truth_rel):
        root = fixtures_dir.parent.parent
        audio_path = root / audio_rel
        if not audio_path.exists():
            pytest.skip(f"TTS fixture missing: {audio_path}")

        segments = whisper_transcriber.transcribe(str(audio_path))
        for i, seg in enumerate(segments):
            assert seg.start >= 0, f"Segment {i}: negative start time"
            assert seg.end > seg.start, f"Segment {i}: end <= start"
            assert seg.text.strip(), f"Segment {i}: empty text"

        starts = [s.start for s in segments]
        assert starts == sorted(starts), "Segments not in chronological order"


# ── User-provided MP3 fixtures ─────────────────────────────────────────────

@pytest.mark.slow
class TestWhisperMP3Accuracy:
    @pytest.mark.parametrize("audio_rel,truth_rel", MP3_FIXTURES)
    def test_wer(self, whisper_transcriber, fixtures_dir, audio_rel, truth_rel):
        root = fixtures_dir.parent.parent
        audio_path = root / audio_rel
        if not audio_path.exists():
            pytest.skip(f"Audio file not found: {audio_path}")

        reference = _load_ground_truth(root, truth_rel)
        if reference is None or reference.startswith("TODO"):
            pytest.skip(
                f"Ground truth not filled in: {truth_rel}\n"
                "  Replace the TODO placeholder with the real transcript."
            )

        segments = whisper_transcriber.transcribe(str(audio_path))
        hypothesis = segments_to_text(segments)
        score = wer(reference, hypothesis)

        assert score < MP3_WER_THRESHOLD, (
            f"WER {score:.1%} exceeds threshold {MP3_WER_THRESHOLD:.0%}\n"
            f"  Reference:  {reference}\n"
            f"  Hypothesis: {hypothesis}"
        )

    @pytest.mark.parametrize("audio_rel,truth_rel", MP3_FIXTURES)
    def test_segments_nonempty(self, whisper_transcriber, fixtures_dir, audio_rel, truth_rel):
        root = fixtures_dir.parent.parent
        audio_path = root / audio_rel
        if not audio_path.exists():
            pytest.skip(f"Audio file not found: {audio_path}")
        reference = _load_ground_truth(root, truth_rel)
        if reference is None or reference.startswith("TODO"):
            pytest.skip(f"Ground truth not filled in: {truth_rel}")

        segments = whisper_transcriber.transcribe(str(audio_path))
        assert len(segments) > 0
